apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: set-mongo-admin
spec:
  rules:
    - name: set-mongo-admin
      match:
        any:
        - resources:
            kinds:
            - MongoDBCommunity
      preconditions:
        all:
        - key: "{{ request.object.spec.users[*].name }}"
          operator: In
          value: "admin"
      mutate:
        foreach:
        - list: "request.object.spec.users"
          patchesJson6902: |-
            - path: "/spec/users/{{elementIndex}}/roles"
              op: add
              value:
                - name: dbAdminAnyDatabase
                  db: admin
                - name: userAdminAnyDatabase
                  db: admin
                - name: clusterAdmin
                  db: admin
                - name: readWriteAnyDatabase
                  db: admin