apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: set-mongo-admin
spec:
  rules:
    - name: set-mongo-admin
      match:
        any:
        - resources:
            kinds:
            - MongoDBCommunity
      preconditions:
        all:
        - key: "{{ request.object.spec.users[0].name }}"
          operator: Equals
          value: "admin"
      mutate:
        patchesJson6902: |-
          - path: "/spec/users/0/roles"
            op: add
            value:
              - name: dbAdminAnyDatabase
                db: admin
              - name: userAdminAnyDatabase
                db: admin
              - name: clusterAdmin
                db: admin