apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: set-mongo-admin
spec:
  rules:
    - name: set-mongo-admin
      match:
        any:
        - resources:
            kinds:
            - MongoDBCommunity
      mutate:
        patchStrategicMerge:
          spec:
          users:
          - name: admin
            roles:
            - name: dbAdminAnyDatabase
              db: admin
            - name: userAdminAnyDatabase
              db: admin
            - name: clusterAdmin
              db: admin