apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: set-volume-size
spec:
  rules:
    - name: set-volume-size
      match:
        any:
        - resources:
            kinds:
            - MongoDBCommunity
      mutate: 
        foreach: 
        - list: "request.object.spec.statefulSet.spec.volumeClaimTemplates"
          patchesJson6902: |-
            - path: "/spec/statefulSet/spec/volumeClaimTemplates/{{elementIndex}}/spec/resources/requests"
              op: add
              value: {"storage" : "5Gi"}  
